### ISSUE TITLE
Buildpack fails on heroku-16/18 stack

### ISSUE THREAD

**Issue by andrecavallari** [Starkast/heroku-buildpack-cmake#17]
Since today 11/12/2019, this buildpack started breaking, and a message "cannot detect buildpack" is shown on CI, I forked it and just changed the detect to `echo 'Cmake' and started working fine

**Comment by dentarg** [comment]
Interesting, just saw #18. Do you use Heroku CI @andrecavallari?

**Comment by andrecavallari** [comment]
@dentarg, yes, I do, and yes, it's breaking on heroku CI, but I sent a fix wich is able to run on any kind of shell

**Comment by dentarg** [comment]
What kind of shell is Heroku CI using?

**Comment by dentarg** [comment]
I think explicit support for Heroku CI needs to be added here, see

* https://devcenter.heroku.com/articles/heroku-ci#supported-languages
* https://devcenter.heroku.com/articles/testpack-api
* https://github.com/HashNuke/heroku-buildpack-elixir/pull/92

**Comment by dentarg** [comment]
Or what do you think @andrecavallari?

**Comment by kbaum** [comment]
We are not using heroku ci but this started breaking for us today too.

**Comment by kbaum** [comment]
Looking at the heroku buildpack documentation on detect, it reads me to like it's trying to determine if the buildpack is valid for the app:

https://devcenter.heroku.com/articles/buildpack-api#bin-detect

If that is true, it would make sense that we would get this error whenever the buildpack returned a non-zero exit status. Not sure why it just started failing though. I modified a fork to always return 0 to get this working for us:

https://github.com/Starkast/heroku-buildpack-cmake/compare/master...coverband-service:master

**Comment by dentarg** [comment]
@kbaum Thanks for clarifying. I understand now. I haven't deployed any app using this buildpack myself lately.

The detect script fails because `cmake` is present. With the [recent update of Heroku stack images](https://devcenter.heroku.com/changelog-items/1713), `cmake` is installed during build time, see https://github.com/heroku/stack-images/pull/150 and https://devcenter.heroku.com/articles/stack-packages.

I think this pretty much makes this buildpack obsolete. :) (Unless, you also need `cmake` at runtime.)

**Comment by kbaum** [comment]
Oh. That explains why it started failing all of the sudden. Thanks for the update!
